# Generated by Django 3.1.7 on 2021-03-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
